// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uca.iw.myjob.domain;

import es.uca.iw.myjob.domain.OfertaTrabajo;
import es.uca.iw.myjob.domain.OfertaTrabajoDataOnDemand;
import es.uca.iw.myjob.reference.EstadoEmpleo;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect OfertaTrabajoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OfertaTrabajoDataOnDemand: @Component;
    
    private Random OfertaTrabajoDataOnDemand.rnd = new SecureRandom();
    
    private List<OfertaTrabajo> OfertaTrabajoDataOnDemand.data;
    
    public OfertaTrabajo OfertaTrabajoDataOnDemand.getNewTransientOfertaTrabajo(int index) {
        OfertaTrabajo obj = new OfertaTrabajo();
        setDescripcion(obj, index);
        setEstadoempleo(obj, index);
        setExperienciaprevia(obj, index);
        setFechaaproxinic(obj, index);
        setFormacion(obj, index);
        setNombre(obj, index);
        setNumvacantes(obj, index);
        setPerfil(obj, index);
        setSueldobruto(obj, index);
        setTipologiacontrato(obj, index);
        return obj;
    }
    
    public void OfertaTrabajoDataOnDemand.setDescripcion(OfertaTrabajo obj, int index) {
        String descripcion = "descripcion_" + index;
        if (descripcion.length() > 255) {
            descripcion = descripcion.substring(0, 255);
        }
        obj.setDescripcion(descripcion);
    }
    
    public void OfertaTrabajoDataOnDemand.setEstadoempleo(OfertaTrabajo obj, int index) {
        EstadoEmpleo estadoempleo = EstadoEmpleo.class.getEnumConstants()[0];
        obj.setEstadoempleo(estadoempleo);
    }
    
    public void OfertaTrabajoDataOnDemand.setExperienciaprevia(OfertaTrabajo obj, int index) {
        String experienciaprevia = "experienciaprevia_" + index;
        obj.setExperienciaprevia(experienciaprevia);
    }
    
    public void OfertaTrabajoDataOnDemand.setFechaaproxinic(OfertaTrabajo obj, int index) {
        Date fechaaproxinic = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaaproxinic(fechaaproxinic);
    }
    
    public void OfertaTrabajoDataOnDemand.setFormacion(OfertaTrabajo obj, int index) {
        String formacion = "formacion_" + index;
        if (formacion.length() > 30) {
            formacion = formacion.substring(0, 30);
        }
        obj.setFormacion(formacion);
    }
    
    public void OfertaTrabajoDataOnDemand.setNombre(OfertaTrabajo obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 30) {
            nombre = nombre.substring(0, 30);
        }
        obj.setNombre(nombre);
    }
    
    public void OfertaTrabajoDataOnDemand.setNumvacantes(OfertaTrabajo obj, int index) {
        String numvacantes = "numvacantes_" + index;
        obj.setNumvacantes(numvacantes);
    }
    
    public void OfertaTrabajoDataOnDemand.setPerfil(OfertaTrabajo obj, int index) {
        String perfil = "perfil_" + index;
        if (perfil.length() > 255) {
            perfil = perfil.substring(0, 255);
        }
        obj.setPerfil(perfil);
    }
    
    public void OfertaTrabajoDataOnDemand.setSueldobruto(OfertaTrabajo obj, int index) {
        Float sueldobruto = new Integer(index).floatValue();
        obj.setSueldobruto(sueldobruto);
    }
    
    public void OfertaTrabajoDataOnDemand.setTipologiacontrato(OfertaTrabajo obj, int index) {
        String tipologiacontrato = "tipologiacontrato_" + index;
        if (tipologiacontrato.length() > 30) {
            tipologiacontrato = tipologiacontrato.substring(0, 30);
        }
        obj.setTipologiacontrato(tipologiacontrato);
    }
    
    public OfertaTrabajo OfertaTrabajoDataOnDemand.getSpecificOfertaTrabajo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OfertaTrabajo obj = data.get(index);
        Long id = obj.getId();
        return OfertaTrabajo.findOfertaTrabajo(id);
    }
    
    public OfertaTrabajo OfertaTrabajoDataOnDemand.getRandomOfertaTrabajo() {
        init();
        OfertaTrabajo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return OfertaTrabajo.findOfertaTrabajo(id);
    }
    
    public boolean OfertaTrabajoDataOnDemand.modifyOfertaTrabajo(OfertaTrabajo obj) {
        return false;
    }
    
    public void OfertaTrabajoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = OfertaTrabajo.findOfertaTrabajoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OfertaTrabajo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OfertaTrabajo>();
        for (int i = 0; i < 10; i++) {
            OfertaTrabajo obj = getNewTransientOfertaTrabajo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
